name = "rhule-aid"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "rhule-aid-db"
database_id = "$DATABASE_ID"

[[kv_namespaces]]
binding = "SCHEDULE_CACHE"
id = "$SCHEDULE_CACHE_ID"

[[kv_namespaces]]
binding = "ROSTER_CACHE"
id = "$ROSTER_CACHE_ID"

[[kv_namespaces]]
binding = "NEWS_CACHE"
id = "$NEWS_CACHE_ID"

[[kv_namespaces]]
binding = "WEATHER_CACHE"
id = "$WEATHER_CACHE_ID"

[vars]
ENVIRONMENT = "production"
OPENWEATHER_API_KEY = "$OPENWEATHER_API_KEY"
