name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Substitute environment variables in wrangler.toml
        run: |
          sed -i 's/\$DATABASE_ID/${{ secrets.DATABASE_ID }}/g' wrangler.toml
          sed -i 's/\$SCHEDULE_CACHE_ID/${{ secrets.SCHEDULE_CACHE_ID }}/g' wrangler.toml
          sed -i 's/\$ROSTER_CACHE_ID/${{ secrets.ROSTER_CACHE_ID }}/g' wrangler.toml
          sed -i 's/\$NEWS_CACHE_ID/${{ secrets.NEWS_CACHE_ID }}/g' wrangler.toml
          sed -i 's/\$WEATHER_CACHE_ID/${{ secrets.WEATHER_CACHE_ID }}/g' wrangler.toml
          sed -i 's/\$OPENWEATHER_API_KEY/${{ secrets.OPENWEATHER_API_KEY }}/g' wrangler.toml

      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy public --project-name=rhule-aid
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
